Fixed United Kingom's 2022 holidays
workalendar/workalendar pull request #677
Opened 2021-08-03 12:37 UTC by mountinash789

Queens Platinum Jubilee has been added to 3rd of June and the Spring bank holiday has been moved to the 2nd of June

- [ ] Tests with a significant number of years to be tested for your calendar.
- [ ] Changelog amended with a mention describing your changes. **Note** *Please do NOT change the version number here. It's the project maintainers' duty.*

2021-08-03 12:46 UTC, ewjoachim commented
Source: https://www.royal.uk/platinum-jubilee-central-weekend

2021-09-10 19:28 UTC, brunobord commented
Could you please rebase from upstream in order to fix Changelog conflicts?

2021-09-10 19:50 UTC, brunobord commented
As a matter of fact, I think you could wait a bit longer. The next PR to be added will be the #675, so I'll tell you when upstream will be ready to be used as base.

2021-09-16 20:40 UTC, brunobord commented
ok, so now you have my green light to rebase from upstream. If you need any help doing these, please do not hesitate to ask ;o)

2021-09-17 11:50 UTC, mountinash789 commented
@brunobord Is that ok?

2021-09-24 09:31 UTC, Natim approved these changes

2021-09-24 09:40 UTC, brunobord requested changes
Something may have gone wrong when you updated from upstream.
Should be an easy fix to commit and move the log entries around.

2021-09-24 09:40 UTC, brunobord commented on Changelog.md
> +- Fixed United Kingdom's 2022 holidays ; Spring Bank Holiday has been moved to the 3rd of June and Queen's Platinum Jubilee added to 2nd of June.
Sorry, but this changelog entry should be in the "master (unreleased)" section at the top of the file.

2021-09-24 09:40 UTC, brunobord commented on Changelog.md
> +- Replace `pyCalverter` with `convertdate` (#536)
This line and the line below are duplicated from the lines 18-19 and should be removed from your patch.

2021-09-24 20:41 UTC, brunobord commented
ouch! a flake8 error :( https://github.com/workalendar/workalendar/pull/677/checks?check_run_id=3704515113

2021-09-26 19:54 UTC, merged

2021-10-01 20:09 UTC, brunobord commented
Your fix is finally part of the latest (16.1.0) release:

* https://pypi.org/project/workalendar/16.1.0/
* https://github.com/workalendar/workalendar/releases/tag/16.1.0

Happy upgrading!